/** PY-01 texts, chapters 00–05. HTML strings; both languages. */
export const CH_A = {
  'page.title': { en: 'How Python thinks · PY-01', ru: 'Как Python думает · PY-01' },
  'page.desc': {
    en: 'Python basics taken apart step by step: names and objects, numbers, strings, types, truth, input, errors, mutable and immutable. Every example runs in the browser with a live memory picture.',
    ru: 'Основы Python по шагам: имена и объекты, числа, строки, типы, истина и ложь, ввод, ошибки, изменяемое и неизменяемое. Каждый пример выполняется в браузере с живой картинкой памяти.',
  },
  'py.osd.stand': { en: 'PYTHON', ru: 'PYTHON' },
  'py.foot.stand': { en: '◀ Python stand', ru: '◀ Стенд Python' },
  'py.foot.next02': { en: 'Next: PY-02 · Flow', ru: 'Дальше: PY-02 · Поток' },
  'foot.stop': { en: '■ END OF TAPE', ru: '■ КОНЕЦ КАССЕТЫ' },
  'foot.src': { en: 'Source code and models:', ru: 'Исходный код и модели:' },

  'hero.eyebrow': { en: 'PY-01 · Python · stand B', ru: 'PY-01 · Python · стенд B' },
  'hero.title': { en: 'How Python thinks', ru: 'Как Python думает' },
  'hero.subtitle': { en: 'names, objects, and the rules of the game', ru: 'имена, объекты и правила игры' },
  'hero.lede': {
    en: 'A program is a list of instructions that the computer follows one line at a time, from top to bottom. This tape shows exactly that: every example runs <b>right here</b>, one step at a time, and the picture on the right shows what Python keeps in memory after each step. Press ▶ PLAY, or walk with the arrows.',
    ru: 'Программа — это список инструкций, которые компьютер выполняет по одной строке сверху вниз. Эта кассета показывает ровно это: каждый пример выполняется <b>прямо здесь</b>, шаг за шагом, а картинка справа показывает, что Python держит в памяти после каждого шага. Жми ▶ ПУСК или иди стрелками.',
  },
  'hero.howto': {
    en: '<p><b>How to read a rig.</b> Left: the code; the yellow line is the one that just ran. Right: <b>memory</b> — boxes are objects, labels in the frame are names, arrows say “this name points to this object”. Below: what the program printed, and one sentence about the step. Inputs at the top of a rig can be edited, the rig replays at once.</p><p><b>To run Python on your own computer</b>: install it from <a href="https://www.python.org/downloads/" target="_blank" rel="noopener">python.org</a>, save a file <code>game.py</code> and run <code>python3 game.py</code> in a terminal. Every rig also has a ▶ RUN IT YOURSELF button that starts a real Python right in the page.</p>',
    ru: '<p><b>Как читать стенд.</b> Слева код; жёлтая строка — та, что только что выполнилась. Справа <b>память</b>: коробки — объекты, бирки в кадре — имена, стрелки говорят «это имя указывает на этот объект». Ниже — что программа напечатала и одна фраза о шаге. Входные данные вверху стенда можно менять, стенд сразу проигрывается заново.</p><p><b>Чтобы запустить Python на своём компьютере</b>: поставь его с <a href="https://www.python.org/downloads/" target="_blank" rel="noopener">python.org</a>, сохрани файл <code>game.py</code> и выполни в терминале <code>python3 game.py</code>. У каждого стенда есть кнопка ▶ ЗАПУСТИТЬ САМОМУ — она включает настоящий Python прямо на странице.</p>',
  },
  'hero.mapH': { en: 'Chapters', ru: 'Главы' },

  /* ---------- 01 print ---------- */
  'ch.print.h2': { en: 'print and the first program', ru: 'print и первая программа' },
  'ch.print.short': { en: 'Text goes in, text comes out. sep, end, and the first bug.', ru: 'Текст внутрь — текст наружу. sep, end и первый баг.' },
  'ch.print.lede': { en: '<code>print()</code> is a function: you hand it things in parentheses, it writes them to the console.', ru: '<code>print()</code> — функция: ты передаёшь ей что-то в скобках, она пишет это в консоль.' },
  'ch.print.body': {
    en: '<p>Text in quotes is a <b>string</b>. Several things separated by commas are printed with a space between them. Two knobs change that: <code>sep=</code> is what goes <i>between</i> the things, <code>end=</code> is what goes <i>after</i> (normally a line break).</p><p>Multiplying a string by a number repeats it. <code>2 + 3</code> without quotes is arithmetic; <code>"2 + 3"</code> with quotes is just five characters.</p>',
    ru: '<p>Текст в кавычках — это <b>строка</b>. Несколько вещей через запятую печатаются через пробел. Две ручки меняют это: <code>sep=</code> — что стоит <i>между</i> вещами, <code>end=</code> — что идёт <i>после</i> (обычно перевод строки).</p><p>Умножить строку на число — значит повторить её. <code>2 + 3</code> без кавычек — арифметика; <code>"2 + 3"</code> в кавычках — просто пять символов.</p>',
  },
  'ch.print.hood': {
    en: '<p><code>print</code> is an ordinary object of type <code>builtin_function_or_method</code>: you can write <code>say = print</code> and then <code>say("hi")</code> works. It converts each argument with <code>str()</code>, joins them with <code>sep</code>, appends <code>end</code>, and writes to <code>sys.stdout</code>, a buffered text stream. The buffer is flushed on a newline when stdout is a terminal, or when you pass <code>flush=True</code>.</p><p>In C# the closest is <code>Console.WriteLine(string.Join(" ", args))</code>; there is no <code>sep</code>/<code>end</code>, so Python’s <code>print</code> is really a tiny formatter.</p>',
    ru: '<p><code>print</code> — обычный объект типа <code>builtin_function_or_method</code>: можно написать <code>say = print</code>, и <code>say("hi")</code> заработает. Он превращает каждый аргумент через <code>str()</code>, склеивает через <code>sep</code>, добавляет <code>end</code> и пишет в <code>sys.stdout</code> — буферизованный текстовый поток. Буфер сбрасывается на переводе строки, если stdout — терминал, или при <code>flush=True</code>.</p><p>В C# ближайший аналог — <code>Console.WriteLine(string.Join(" ", args))</code>; там нет <code>sep</code>/<code>end</code>, так что <code>print</code> в Python — это маленький форматировщик.</p>',
  },
  'rig.hello.title': { en: 'print: sep, end and repetition', ru: 'print: sep, end и повторение' },
  'rig.hello.l2': { en: () => '<code>sep=" · "</code> replaced the default space between the two words.', ru: () => '<code>sep=" · "</code> заменил пробел между словами по умолчанию.' },
  'rig.hello.l3': { en: () => '<code>end=" "</code>: no line break, so the next print continues the same line.', ru: () => '<code>end=" "</code>: перевода строки нет, следующий print продолжит ту же строку.' },
  'rig.hello.l5': { en: () => 'A string times a number: the text is repeated that many times.', ru: () => 'Строка умножить на число: текст повторяется столько раз.' },
  'rig.hello.l6': { en: () => 'An empty <code>print()</code> prints only the line break.', ru: () => 'Пустой <code>print()</code> печатает только перевод строки.' },
  'rig.hello.l7': { en: () => '<code>2 + 3</code> is computed first (5), then <code>2 + 3 == 5</code> is a comparison: <code>True</code>.', ru: () => 'Сначала считается <code>2 + 3</code> (5), затем <code>2 + 3 == 5</code> — это сравнение: <code>True</code>.' },

  /* ---------- 02 names ---------- */
  'ch.names.h2': { en: 'Names and objects', ru: 'Имена и объекты' },
  'ch.names.short': { en: 'A variable is a label on a box, not the box. is vs ==.', ru: 'Переменная — бирка на коробке, а не коробка. is против ==.' },
  'ch.names.lede': { en: 'The most important picture on this tape: <b>a name points to an object</b>. Assignment moves the label, it never copies the box.', ru: 'Самая важная картинка на кассете: <b>имя указывает на объект</b>. Присваивание переставляет бирку, а не копирует коробку.' },
  'ch.names.body': {
    en: '<p>Watch <code>a = 5</code>: Python creates an object (the integer 5) and sticks the label <code>a</code> on it. <code>b = a</code> does <b>not</b> make a second 5 — it sticks a second label on the <i>same</i> object. Then <code>a = 6</code> moves the label <code>a</code> to a new object; <code>b</code> keeps pointing at 5.</p><p>Two questions you can ask: <code>a == b</code> — “are the values equal?”, and <code>a is b</code> — “is it the very same object?”.</p>',
    ru: '<p>Смотри на <code>a = 5</code>: Python создаёт объект (целое число 5) и вешает на него бирку <code>a</code>. <code>b = a</code> <b>не</b> делает второе число 5 — это вторая бирка на <i>том же</i> объекте. Затем <code>a = 6</code> переносит бирку <code>a</code> на новый объект; <code>b</code> по-прежнему указывает на 5.</p><p>Два вопроса, которые можно задать: <code>a == b</code> — «равны ли значения?», и <code>a is b</code> — «это тот же самый объект?».</p>',
  },
  'ch.names.body2': {
    en: '<p>Here is a surprise worth knowing: Python keeps the small integers from −5 to 256 ready-made and reuses them, so two separate <code>7</code> are the same object, while a <code>1000</code> written in the code and a <code>1000</code> computed at run time (<code>int("1000")</code>) are two different boxes. That is why you compare values with <code>==</code> and use <code>is</code> only for <code>None</code>.</p>',
    ru: '<p>Сюрприз, который стоит знать: маленькие целые от −5 до 256 Python держит готовыми и переиспользует, поэтому два отдельных <code>7</code> — один и тот же объект, а <code>1000</code>, записанное в коде, и <code>1000</code>, вычисленное во время работы (<code>int("1000")</code>), — две разные коробки. Поэтому значения сравнивают через <code>==</code>, а <code>is</code> оставляют для <code>None</code>.</p>',
  },
  'ch.names.hood': {
    en: '<p>Every CPython object is a struct with a reference count and a pointer to its type. A name is an entry in a dictionary (the module’s globals or the frame’s locals) whose value is a pointer to the object. <code>id(x)</code> returns that pointer; <code>x is y</code> is pointer equality. Assignment increments the refcount of the new object and decrements the old one’s; when a count reaches zero the object is freed immediately — no garbage collector needed for the common case (the collector only handles reference cycles).</p><p>The small-int cache and string interning of identifier-like literals are implementation details of CPython, not language rules: never rely on <code>is</code> for numbers or strings.</p><p>For a C# developer: Python has no value types. Even <code>5</code> is a heap object; what feels like “copy semantics” of ints is just immutability — nobody can change the 5 under your feet, so sharing it is safe.</p>',
    ru: '<p>Каждый объект CPython — структура со счётчиком ссылок и указателем на тип. Имя — запись в словаре (globals модуля или locals кадра), значение которой — указатель на объект. <code>id(x)</code> возвращает этот указатель; <code>x is y</code> — сравнение указателей. Присваивание увеличивает счётчик у нового объекта и уменьшает у старого; когда счётчик доходит до нуля, объект освобождается сразу — сборщик мусора нужен только для циклов ссылок.</p><p>Кэш маленьких int и интернирование строк-идентификаторов — детали реализации CPython, а не правила языка: никогда не полагайся на <code>is</code> для чисел и строк.</p><p>Для C#-разработчика: в Python нет value types. Даже <code>5</code> — объект в куче; то, что похоже на «копирование» int, — просто неизменяемость: никто не может поменять пятёрку у тебя под ногами, поэтому делить её безопасно.</p>',
  },
  'rig.names.title': { en: 'Labels move, boxes stay', ru: 'Бирки переезжают, коробки остаются' },
  'rig.names.l2': { en: () => '<code>b = a</code>: no new object. Both names point at the same box — look at the two arrows.', ru: () => '<code>b = a</code>: нового объекта нет. Оба имени указывают на одну коробку — смотри на две стрелки.' },
  'rig.names.l3': { en: e => `<code>a</code> moves to a new object <code>${e.repr}</code>. <code>b</code> did not move.`, ru: e => `<code>a</code> переезжает на новый объект <code>${e.repr}</code>. <code>b</code> никуда не делось.` },
  'rig.isvs.title': { en: 'is versus ==', ru: 'is против ==' },
  'rig.isvs.l5': { en: () => 'Small ints are cached: both names point to one object, so <code>is</code> is True.', ru: () => 'Маленькие int кэшируются: оба имени указывают на один объект, поэтому <code>is</code> даёт True.' },
  'rig.isvs.l6': { en: () => 'The literal 1000 and the 1000 built by <code>int("1000")</code> are two boxes: equal values, <code>is</code> is False.', ru: () => 'Литерал 1000 и 1000, собранное через <code>int("1000")</code>, — две коробки: значения равны, но <code>is</code> даёт False.' },

  /* ---------- 03 numbers ---------- */
  'ch.numbers.h2': { en: 'Numbers', ru: 'Числа' },
  'ch.numbers.short': { en: 'int has no limit, / always gives a float, // and % share the leftovers.', ru: 'У int нет предела, / всегда даёт float, // и % делят остаток.' },
  'ch.numbers.lede': { en: 'Two kinds of numbers: <code>int</code> (whole, unlimited) and <code>float</code> (with a point, approximate).', ru: 'Два вида чисел: <code>int</code> (целое, без предела) и <code>float</code> (с точкой, приблизительное).' },
  'ch.numbers.body': {
    en: '<p>In most languages a whole number fits in 32 or 64 bits and overflows. Python’s <code>int</code> just grows: <code>2 ** 100</code> has 31 digits and that is fine. <code>**</code> is power.</p><p>Division is where beginners trip: <code>7 / 2</code> is <code>3.5</code> (always a float, even <code>10 / 2</code> is <code>5.0</code>), <code>7 // 2</code> is <code>3</code> (floor), <code>7 % 2</code> is <code>1</code> (remainder). With negatives, <code>//</code> rounds <i>down</i>: <code>-7 // 2</code> is <code>-4</code>, and the remainder takes the sign of the divisor. <code>divmod</code> gives both at once.</p><p><code>score += 5</code> is a short way to write <code>score = score + 5</code>.</p>',
    ru: '<p>В большинстве языков целое число помещается в 32 или 64 бита и переполняется. <code>int</code> в Python просто растёт: у <code>2 ** 100</code> 31 цифра, и это нормально. <code>**</code> — степень.</p><p>Деление — место, где спотыкаются новички: <code>7 / 2</code> даёт <code>3.5</code> (всегда float, даже <code>10 / 2</code> — это <code>5.0</code>), <code>7 // 2</code> даёт <code>3</code> (округление вниз), <code>7 % 2</code> даёт <code>1</code> (остаток). С отрицательными <code>//</code> округляет <i>вниз</i>: <code>-7 // 2</code> равно <code>-4</code>, а остаток берёт знак делителя. <code>divmod</code> даёт оба сразу.</p><p><code>score += 5</code> — короткая запись для <code>score = score + 5</code>.</p>',
  },
  'ch.numbers.body2': {
    en: '<p>Floats are stored in binary, and <code>0.1</code> cannot be written exactly in binary — just like ⅓ cannot be written exactly in decimal. So <code>0.1 + 0.2</code> is <code>0.30000000000000004</code> and is <b>not</b> equal to <code>0.3</code>. This is not a Python bug; every language with IEEE 754 doubles does it. Compare floats with <code>math.isclose</code>, or round them, or use integers (count cents, not dollars).</p>',
    ru: '<p>Float хранится в двоичном виде, а <code>0.1</code> нельзя точно записать в двоичном — так же, как ⅓ нельзя точно записать десятичной дробью. Поэтому <code>0.1 + 0.2</code> равно <code>0.30000000000000004</code> и <b>не</b> равно <code>0.3</code>. Это не баг Python: так делает любой язык с double по IEEE 754. Сравнивай float через <code>math.isclose</code>, округляй или считай в целых (копейки, а не рубли).</p>',
  },
  'ch.numbers.hood': {
    en: '<p>CPython ints are arrays of 30-bit “digits”; arithmetic is schoolbook for small sizes and Karatsuba for large ones. <code>sys.getsizeof(0)</code> is 28 bytes, each extra 30 bits adds 4. Floats are C doubles (IEEE 754, 53-bit mantissa), 24 bytes with the object header. <code>repr(float)</code> prints the <i>shortest</i> decimal that round-trips, which is why you see 0.1 and not 0.1000000000000000055511151231257827.</p><p><code>round()</code> uses banker’s rounding on the exact binary value: <code>round(2.5)</code> is 2, <code>round(3.5)</code> is 4, and <code>round(2.675, 2)</code> is 2.67 because 2.675 is really 2.67499999…. For money use <code>decimal.Decimal</code>; for exact fractions, <code>fractions.Fraction</code>.</p><div class="cmp"><div><span class="lbl">C#</span><code>7 / 2 == 3</code> (integer division), <code>int</code> overflows silently unless <code>checked</code>, <code>%</code> keeps the sign of the dividend: <code>-7 % 2 == -1</code>.</div><div><span class="lbl">Python</span><code>7 / 2 == 3.5</code>, <code>7 // 2 == 3</code>, ints never overflow, <code>-7 % 2 == 1</code> (sign of the divisor).</div></div>',
    ru: '<p>int в CPython — массив 30-битных «цифр»; арифметика школьная для малых чисел и Карацубы для больших. <code>sys.getsizeof(0)</code> — 28 байт, каждые лишние 30 бит добавляют 4. float — это C double (IEEE 754, 53-битная мантисса), 24 байта с заголовком объекта. <code>repr(float)</code> печатает <i>кратчайшую</i> десятичную запись, которая восстанавливается обратно, — поэтому ты видишь 0.1, а не 0.1000000000000000055511151231257827.</p><p><code>round()</code> округляет к ближайшему чётному по точному двоичному значению: <code>round(2.5)</code> — 2, <code>round(3.5)</code> — 4, а <code>round(2.675, 2)</code> — 2.67, потому что 2.675 на самом деле 2.67499999…. Для денег есть <code>decimal.Decimal</code>, для точных дробей — <code>fractions.Fraction</code>.</p><div class="cmp"><div><span class="lbl">C#</span><code>7 / 2 == 3</code> (целочисленное деление), <code>int</code> молча переполняется без <code>checked</code>, <code>%</code> берёт знак делимого: <code>-7 % 2 == -1</code>.</div><div><span class="lbl">Python</span><code>7 / 2 == 3.5</code>, <code>7 // 2 == 3</code>, int не переполняется, <code>-7 % 2 == 1</code> (знак делителя).</div></div>',
  },
  'rig.bigint.title': { en: 'Unlimited ints and the three divisions', ru: 'Бесконечные int и три деления' },
  'rig.bigint.l1': { en: e => `<code>2 ** n</code>: a huge int is just a bigger box — <code>${e.repr.length > 30 ? e.repr.slice(0, 27) + '…' : e.repr}</code>.`, ru: e => `<code>2 ** n</code>: огромный int — просто коробка побольше: <code>${e.repr.length > 30 ? e.repr.slice(0, 27) + '…' : e.repr}</code>.` },
  'rig.bigint.l7': { en: () => '<code>score += 5</code> made a <b>new</b> int and moved the name: ints are immutable.', ru: () => '<code>score += 5</code> создал <b>новый</b> int и переставил имя: int неизменяем.' },
  'rig.bigint.l9': { en: () => '<code>/</code> → float 3.5; <code>//</code> → whole part 3; <code>%</code> → remainder 1.', ru: () => '<code>/</code> → float 3.5; <code>//</code> → целая часть 3; <code>%</code> → остаток 1.' },
  'rig.bigint.l10': { en: () => '<code>-7 // 2</code> rounds down to −4, and the remainder is 1 so that <code>-4 * 2 + 1 == -7</code>.', ru: () => '<code>-7 // 2</code> округляется вниз до −4, а остаток 1, чтобы <code>-4 * 2 + 1 == -7</code>.' },
  'rig.floats.title': { en: '0.1 + 0.2 and friends', ru: '0.1 + 0.2 и компания' },
  'rig.floats.l1': { en: () => 'The sum is stored as the nearest binary fraction — not exactly 0.3.', ru: () => 'Сумма хранится как ближайшая двоичная дробь — не ровно 0.3.' },
  'rig.floats.l3': { en: () => '<code>==</code> on floats compares the exact binary values: False.', ru: () => '<code>==</code> у float сравнивает точные двоичные значения: False.' },
  'rig.floats.l5': { en: () => '<code>math.isclose</code> allows a tiny relative difference — the right tool.', ru: () => '<code>math.isclose</code> допускает крошечную относительную разницу — правильный инструмент.' },
  'rig.floats.l10': { en: () => 'Banker’s rounding: halves go to the even neighbour; 2.675 is secretly 2.67499…', ru: () => 'Округление к чётному: половинки идут к чётному соседу; 2.675 втайне равно 2.67499…' },

  /* ---------- 04 strings ---------- */
  'ch.strings.h2': { en: 'Strings', ru: 'Строки' },
  'ch.strings.short': { en: 'Indexes from 0 and from −1, slices, methods, and why strings never change.', ru: 'Индексы с 0 и с −1, срезы, методы и почему строки не меняются.' },
  'ch.strings.lede': { en: 'A string is a row of characters. You can look at any of them by number — counting from <b>0</b> at the front and from <b>−1</b> at the back.', ru: 'Строка — ряд символов. На любой можно посмотреть по номеру: считая с <b>0</b> спереди и с <b>−1</b> сзади.' },
  'ch.strings.body': {
    en: '<p><code>len(word)</code> is the number of characters. <code>word[0]</code> is the first, <code>word[-1]</code> the last. A <b>slice</b> <code>word[1:4]</code> takes characters 1, 2, 3 — the stop index is <i>not</i> included, so <code>word[:3] + word[3:]</code> is the whole word again. A third number is the step: <code>word[::2]</code> is every second letter and <code>word[::-1]</code> walks backwards, which is the classic way to reverse a string.</p><p>Methods are actions attached to the string: <code>word.upper()</code>, <code>word.title()</code>. They return a <b>new</b> string. <code>"a" in word</code> asks whether a letter (or a whole substring) is inside.</p>',
    ru: '<p><code>len(word)</code> — число символов. <code>word[0]</code> — первый, <code>word[-1]</code> — последний. <b>Срез</b> <code>word[1:4]</code> берёт символы 1, 2, 3 — индекс stop <i>не</i> входит, поэтому <code>word[:3] + word[3:]</code> снова даёт слово целиком. Третье число — шаг: <code>word[::2]</code> — каждая вторая буква, а <code>word[::-1]</code> идёт задом наперёд — классический способ перевернуть строку.</p><p>Методы — действия, прикреплённые к строке: <code>word.upper()</code>, <code>word.title()</code>. Они возвращают <b>новую</b> строку. <code>"a" in word</code> спрашивает, есть ли буква (или целый кусок) внутри.</p>',
  },
  'ch.strings.body2': {
    en: '<p>Play with the three slice numbers below. Rules: a missing start means “from the beginning”, a missing stop means “to the end”, negative numbers count from the back, and a negative step reverses the direction (then start should be the bigger index). Indexes past the end are quietly clamped in slices — but a single index past the end is an <code>IndexError</code>.</p>',
    ru: '<p>Покрути три числа среза внизу. Правила: пропущенный start значит «с начала», пропущенный stop — «до конца», отрицательные считают с конца, отрицательный шаг разворачивает направление (тогда start должен быть больше). Индексы за концом в срезах тихо обрезаются, а вот одиночный индекс за концом — это <code>IndexError</code>.</p>',
  },
  'ch.strings.body3': {
    en: '<p>Strings are <b>immutable</b>: once made, a string never changes. You cannot fix a letter in place — the first rig below proves it with a <code>TypeError</code>. What you do instead is build a <i>new</i> string from pieces and point the name at it. The old string still exists as long as something points to it.</p>',
    ru: '<p>Строки <b>неизменяемы</b>: созданная строка никогда не меняется. Нельзя исправить букву на месте — первый стенд ниже доказывает это ошибкой <code>TypeError</code>. Вместо этого собирают <i>новую</i> строку из кусков и направляют имя на неё. Старая строка живёт, пока на неё кто-то указывает.</p>',
  },
  'ch.strings.hood': {
    en: '<p>A <code>str</code> is a sequence of Unicode code points, not bytes. CPython stores it compactly (PEP 393): 1 byte per character if everything fits in Latin-1, 2 if it fits in the BMP, 4 otherwise — so <code>"привет"</code> takes 2 bytes per letter and an emoji takes 4. <code>len("😀")</code> is 1 (one code point), but some emoji are several code points glued by zero-width joiners. Encoding to UTF-8 for files and networks is a separate step: <code>"é".encode()</code> is two bytes.</p><p>Because strings are immutable, <code>s += "x"</code> in a loop copies the whole string each time: O(n²). Collect pieces in a list and <code>"".join(pieces)</code>. Slices create new strings (copies), there are no string views.</p><p>C# strings are immutable too and are UTF-16 (<code>"😀".Length == 2</code>); Python indexes by code point, which is usually what you want.</p>',
    ru: '<p><code>str</code> — последовательность кодовых точек Unicode, а не байтов. CPython хранит её компактно (PEP 393): 1 байт на символ, если всё влезает в Latin-1, 2 — если в BMP, иначе 4; так что <code>"привет"</code> занимает по 2 байта на букву, а эмодзи — 4. <code>len("😀")</code> равен 1 (одна кодовая точка), но некоторые эмодзи — несколько точек, склеенных соединителями нулевой ширины. Кодирование в UTF-8 для файлов и сети — отдельный шаг: <code>"é".encode()</code> — два байта.</p><p>Из-за неизменяемости <code>s += "x"</code> в цикле каждый раз копирует всю строку: O(n²). Собирай куски в список и делай <code>"".join(pieces)</code>. Срезы создают новые строки (копии), «окон» на строку нет.</p><p>Строки в C# тоже неизменяемы, но это UTF-16 (<code>"😀".Length == 2</code>); Python индексирует по кодовым точкам, что обычно и нужно.</p>',
  },
  'rig.strindex.title': { en: 'Indexes, slices, methods', ru: 'Индексы, срезы, методы' },
  'rig.strindex.l3': { en: () => 'Index 0 is the first character, −1 the last. Each index gives a one-character string.', ru: () => 'Индекс 0 — первый символ, −1 — последний. Каждый индекс даёт строку из одного символа.' },
  'rig.strindex.l4': { en: () => '<code>[1:4]</code> → positions 1, 2, 3. The stop (4) is left out.', ru: () => '<code>[1:4]</code> → позиции 1, 2, 3. Stop (4) не входит.' },
  'rig.strindex.l6': { en: () => 'Step −1 walks from the end to the start: the word reversed.', ru: () => 'Шаг −1 идёт от конца к началу: слово задом наперёд.' },
  'rig.strindex.l8': { en: () => 'Methods return new strings; <code>word</code> itself is unchanged.', ru: () => 'Методы возвращают новые строки; сам <code>word</code> не изменился.' },
  'rig.slices.title': { en: 'Slice lab: start, stop, step', ru: 'Лаборатория срезов: start, stop, step' },
  'rig.slices.stage': { en: 'the string', ru: 'строка' },
  'rig.slices.l5': { en: e => `The green cells are what <code>s[start:stop:step]</code> picked: <code>${e.repr}</code>.`, ru: e => `Зелёные клетки — то, что выбрал <code>s[start:stop:step]</code>: <code>${e.repr}</code>.` },
  'rig.strimm.title': { en: 'Trying to change a letter in place', ru: 'Попытка поменять букву на месте' },
  'rig.strimm.l2:error': { en: () => '<code>str</code> does not support item assignment — strings are immutable. Not a bug in your head; a rule.', ru: () => '<code>str</code> не поддерживает присваивание по индексу — строки неизменяемы. Это не твоя ошибка, а правило.' },
  'rig.strnew.title': { en: 'Build a new string instead', ru: 'Собери новую строку вместо этого' },
  'rig.strnew.l2': { en: () => 'Pieces glued with <code>+</code> form a brand-new object; <code>name</code> still points at the old one.', ru: () => 'Куски, склеенные через <code>+</code>, дают совершенно новый объект; <code>name</code> всё ещё указывает на старый.' },
  'rig.strnew.l5': { en: () => 'Now the label <code>name</code> moves. The old string has no names left and will be freed.', ru: () => 'Теперь бирка <code>name</code> переезжает. У старой строки не осталось имён — её освободят.' },

  /* ---------- 05 types ---------- */
  'ch.types.h2': { en: 'Types and conversions', ru: 'Типы и преобразования' },
  'ch.types.short': { en: 'Everything has a type; Python never guesses, you convert explicitly.', ru: 'У всего есть тип; Python не угадывает, ты преобразуешь явно.' },
  'ch.types.lede': { en: 'Every object knows its type: <code>type(42)</code> is <code>int</code>, <code>type("42")</code> is <code>str</code>. Same digits, different things.', ru: 'Каждый объект знает свой тип: <code>type(42)</code> — <code>int</code>, <code>type("42")</code> — <code>str</code>. Одни и те же цифры, разные вещи.' },
  'ch.types.body': {
    en: '<p>The basic types you will meet on this tape: <code>int</code>, <code>float</code>, <code>str</code>, <code>bool</code> (only <code>True</code> and <code>False</code>), <code>NoneType</code> (only <code>None</code> — “nothing here”), plus containers <code>list</code> and <code>tuple</code> that we open in PY-03. <code>type(x).__name__</code> gives the name as a string, <code>isinstance(x, int)</code> asks “is x an int (or a subtype)?”. Fun fact: <code>bool</code> is a subtype of <code>int</code>, so <code>True + True</code> is 2.</p>',
    ru: '<p>Базовые типы этой кассеты: <code>int</code>, <code>float</code>, <code>str</code>, <code>bool</code> (только <code>True</code> и <code>False</code>), <code>NoneType</code> (только <code>None</code> — «здесь ничего»), плюс контейнеры <code>list</code> и <code>tuple</code>, которые откроем в PY-03. <code>type(x).__name__</code> даёт имя строкой, <code>isinstance(x, int)</code> спрашивает «x — это int (или подтип)?». Забавный факт: <code>bool</code> — подтип <code>int</code>, поэтому <code>True + True</code> равно 2.</p>',
  },
  'ch.types.body2': {
    en: '<p>Python is <b>strongly</b> typed: it never silently turns <code>"12"</code> into 12. <code>"12" + 3</code> is a <code>TypeError</code>; you decide what you meant: <code>int("12") + 3</code> gives 15, <code>"12" + str(3)</code> gives <code>"123"</code>. And it is <b>dynamically</b> typed: a name can point to an int now and a string later — the type belongs to the object, not to the name. In the rig, change <code>a</code> to <code>"twelve"</code> and watch which line fails.</p>',
    ru: '<p>Python типизирован <b>строго</b>: он никогда молча не превратит <code>"12"</code> в 12. <code>"12" + 3</code> — это <code>TypeError</code>; ты решаешь, что имел в виду: <code>int("12") + 3</code> даёт 15, <code>"12" + str(3)</code> даёт <code>"123"</code>. И типизирован <b>динамически</b>: имя может указывать на int сейчас и на строку потом — тип принадлежит объекту, а не имени. На стенде замени <code>a</code> на <code>"twelve"</code> и посмотри, какая строка упадёт.</p>',
  },
  'ch.types.hood': {
    en: '<p>“Dynamic” means types are checked at run time; “strong” means no implicit coercion between unrelated types (the only automatic promotions are numeric: int → float → complex, and bool → int). Type hints like <code>x: int = 5</code> are annotations that the interpreter stores but does not check — tools like mypy or Pyright check them before running. PY-05 covers that.</p><p>Every value carries a pointer to its type object; <code>type(x)</code> just returns it. Types themselves are objects of type <code>type</code>, which is its own type — the circle closes at <code>type(type) is type</code>.</p><div class="cmp"><div><span class="lbl">C#</span>Static typing: <code>int x = "12";</code> is a compile error; <code>"12" + 3</code> compiles to <code>"123"</code> (implicit ToString).</div><div><span class="lbl">Python</span>Checked when the line runs; <code>"12" + 3</code> raises; <code>str(3)</code> or <code>int("12")</code> makes the intent explicit.</div></div>',
    ru: '<p>«Динамическая» — типы проверяются во время выполнения; «строгая» — нет неявных преобразований между несвязанными типами (автоматические только числовые: int → float → complex и bool → int). Подсказки типов вроде <code>x: int = 5</code> — аннотации, которые интерпретатор хранит, но не проверяет; их проверяют mypy или Pyright до запуска. Про это в PY-05.</p><p>Каждое значение несёт указатель на объект-тип; <code>type(x)</code> просто возвращает его. Сами типы — объекты типа <code>type</code>, который сам себе тип: круг замыкается на <code>type(type) is type</code>.</p><div class="cmp"><div><span class="lbl">C#</span>Статическая типизация: <code>int x = "12";</code> — ошибка компиляции; <code>"12" + 3</code> компилируется в <code>"123"</code> (неявный ToString).</div><div><span class="lbl">Python</span>Проверка в момент выполнения строки; <code>"12" + 3</code> падает; <code>str(3)</code> или <code>int("12")</code> делают намерение явным.</div></div>',
  },
  'rig.types.title': { en: 'Everything has a type', ru: 'У всего есть тип' },
  'rig.types.l3': { en: e => `<code>repr</code> shows the value the way Python sees it, <code>type(...).__name__</code> names its type: <code>${e.printed.trim()}</code>.`, ru: e => `<code>repr</code> показывает значение так, как его видит Python, а <code>type(...).__name__</code> называет тип: <code>${e.printed.trim()}</code>.` },
  'rig.convert.title': { en: 'Convert, or Python refuses', ru: 'Преобразуй, иначе Python откажется' },
  'rig.convert.l3': { en: () => '<code>int(a)</code> turns the text into a number first; then it is ordinary addition.', ru: () => '<code>int(a)</code> сначала превращает текст в число; дальше обычное сложение.' },
  'rig.convert.l4': { en: () => '<code>str(b)</code> turns the number into text; <code>+</code> on two strings glues them.', ru: () => '<code>str(b)</code> превращает число в текст; <code>+</code> у двух строк склеивает их.' },
  'rig.convert.l6': { en: () => 'A string times an int is repetition — this one works, perhaps not what you wanted.', ru: () => 'Строка умножить на int — повторение; это работает, хотя, возможно, не то, что ты хотел.' },
  'rig.convert.l7:error': { en: () => '<code>str + int</code>: Python will not guess whether you meant 15 or "123". It raises <code>TypeError</code>.', ru: () => '<code>str + int</code>: Python не станет угадывать, 15 ты хотел или "123". Он бросает <code>TypeError</code>.' },
};
